/* Source - https://www.lintcode.com/problem/4-keys-keyboard/description/
   Author - Shivam Arora
*/
#include <bits/stdc++.h>
using namespace std;

int maxA(int N) {
    int dp[N + 1];
    
    for(int i = 1; i <= N; i++) {
        dp[i] = i;
        
        if(i > 6) {
            for(int j = 1; j <= i - 3; j++)
                dp[i] = max(dp[i], dp[j] + dp[j] * (i - j - 2));
        }
    }
    
    return dp[N];
}

int main()
{
    int N;

    cout<<"Enter the value of N: ";
    cin>>N;

    cout<<"Maximum number of A's generated by pressing "<<N<<" keys: "<<maxA(N)<<endl;
}